Overwrite chart name with name from config when mismatch

diff --git a/bin/out b/bin/out
--- a/bin/out
+++ b/bin/out
@@ -14,8 +14,33 @@ CHART_DIR=$(echo "$config" | jq -r ".params.chart")
 CHART_VERSION=$(echo "$config" | jq -r ".params.version_file" | xargs cat)
 CHART_APP_VERSION=$(echo "$config" | jq -r ".params.app_version_file" | xargs cat)
 
-CHART_NAME=$(helm show chart ${CHART_DIR} | grep "^name: " | cut -d' ' -f2)
-log "🕵️ Chart name: $GREEN$CHART_NAME"
+CHART_YAML_FILE=Chart.yaml
+CHART_YAML=${CHART_DIR}/${CHART_YAML_FILE}
+
+if [ ! -f ${CHART_YAML} ]
+then
+  log "😵 $RED$CHART_YAML_FILE$NC not found in $CHART_DIR"
+  exit 1
+fi
+
+function readChartName {
+  helm show chart ${CHART_DIR} | grep "^name: " | cut -d' ' -f2
+}
+
+EFFECTIVE_CHART_NAME=$(readChartName)
+if [[ "$CHART_NAME" != "$EFFECTIVE_CHART_NAME" ]]
+then
+  log "⚠️ Chart name $RED$EFFECTIVE_CHART_NAME$NC in $CHART_YAML_FILE does not match config. Overriding with $GREEN$CHART_NAME$NC..."
+  sed -i '/^name:/d' ${CHART_YAML}
+  echo -e "\nname: $CHART_NAME" >> ${CHART_YAML}
+  if [[ "$CHART_NAME" != "$(readChartName)" ]]
+  then
+    log "😵😵😵 Failed setting chart name $RED$CHART_NAME$NC in $RED$$CHART_YAML"
+    exit 1
+  fi
+else
+  log "🕵️ Chart name: $GREEN$CHART_NAME"
+fi
 
 REPO_ADDRESS=s3://${S3_BUCKET_NAME}/${S3_BUCKET_PATH}
 
